### ISSUE TITLE
Tailing the cloud watch logs 

### ISSUE THREAD

**Issue by konyaj** [TylerBrock/saw#12]
Hi

I have started using the saw tool. It's really a great tool but I found that there is no flag available to tail the logs which is making it cumbersome and time consuming to load the logs.

**Comment by TylerBrock** [comment]
Hi! There is no flag for that because it's a subcommand `watch`:

To tail a particular group use `saw watch <log group>`

**Comment by TylerBrock** [comment]
Closing this because I haven't heard back from you in a couple days. Feel free to re-open if you need more information.
