### ISSUE TITLE
Display the stream name and datetime in `saw get`

### ISSUE THREAD

**Issue by will-ockmore** [TylerBrock/saw#13]
Currently `saw get` simply [prints the raw log message](https://github.com/TylerBrock/saw/blob/master/blade/blade.go#L97), would it be possible for the format to match the output of `saw watch`?

Happy to have a look into this myself when I get some spare time!

**Comment by TylerBrock** [comment]
Not at the moment but would be easy to add this functionality. Great idea for a feature.

**Comment by TylerBrock** [comment]
This wound up in the v0.2.0 milestone and release, crossed off a TODO and is now reflected in the changelog as of https://github.com/TylerBrock/saw/commit/0ad6c7c38a816d1d8052909f135cf490e69673f9. Thanks Will!

**Comment by will-ockmore** [comment]
No probs!
