### ISSUE TITLE
"Get" sample in readme is incomplete

### ISSUE THREAD

**Issue by MdNor** [TylerBrock/saw#16]
I'm not sure if this issue is specific to my environment but
`saw get production --prefix api --start 2018-06-26 --stop 2018-06-28`
doesn't work for me. I have to specify the datetime as per [RFC 3339](https://tools.ietf.org/html/rfc3339).

This is working
`saw get production --prefix api --start 2018-06-26T00:00:00Z --stop 2018-06-28T00:00:00Z`

You may want to revise that portion of the document. The rest is working for me.

**Environment**

- Ubuntu 12.04 (yeah, I know)
- go version go1
- saw v0.1.8

Anyway great tool. Saves me headache trying to figure out CloudWatch API/SDK. 
Thanks.

**Comment by TylerBrock** [comment]
It's kind of lame that we require the full timestamp. I think it would be nice if we interpreted the date alone as a full datetime. Thoughts?

**Comment by MdNor** [comment]
> It's kind of lame that we require the full timestamp. I think it would be nice if we interpreted the date alone as a full datetime. Thoughts?

Agree. That is default behavior with most other tools that many already familiar with.
At least, that's how I noticed this in the first place.
