### ISSUE TITLE
Have old releases been removed?

### ISSUE THREAD

**Issue by rjnienaber** [TylerBrock/saw#35]
I feel like I'm missing something really obvious here but didn't there used to be releases for a `1.2.1` version available from GitHub? I add this to a Dockerfile on the 6 Dec 2018:

```
# install saw
RUN wget https://github.com/TylerBrock/saw/releases/download/v1.2.1/saw_1.2.1_linux_amd64.tar.gz \
    && tar -xzvf saw_1.2.1_linux_amd64.tar.gz saw \
    && mv saw /usr/local/bin \
    && rm saw_1.2.1_linux_amd64.tar.gz
```

This is failing now and when I look at the releases page, I only see a `0.2.2` version. I did try and look through past issues and pull requests but nothing stands out.

**Comment by hauntingEcho** [comment]
It looks like 0.2.1 was released in Oct 2018, maybe it was a typo?

https://github.com/TylerBrock/saw/releases

**Comment by rjnienaber** [comment]
Not sure what happened because I'm positive that my Docker image was getting built. Regardless, it's a year later and we've stopped using `saw` in the meantime. There's no point in keeping this issue around.
