### ISSUE TITLE
Cost regarding AWS CloudWatch API calls

### ISSUE THREAD

**Issue by gustavomassa** [TylerBrock/saw#59]
Hello, thank you for this amazing project.

I have some questions regarding the cost of watching/filtering log streams, how many API calls the tool will do to filter one stream? And if I want to tail/watch the log stream forever, the tool does one API call to start it, or has some kind of pooling/event to update/check if new data is available?

**Comment by Clasyc** [comment]
I may be wrong, but from a quick look, it seems it makes call [every second](https://github.com/TylerBrock/saw/blob/a39981d16e11e258fd67d89cb36d6e1e2629382e/blade/blade.go#L163) when pooling.
